### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by debugwangz** [faebstn96/helix2fan#2]
I got this error when I tried to run the codes
Traceback (most recent call last):
  File "/home/wangzhe/wangzhe2/SV_Algorithms/helix2fan-master/main.py", line 67, in <module>
    run(parser)
  File "/home/wangzhe/wangzhe2/SV_Algorithms/helix2fan-master/main.py", line 18, in run
    raw_projections, parser = read_dicom(parser)
  File "/home/wangzhe/wangzhe2/SV_Algorithms/helix2fan-master/read_data.py", line 82, in read_dicom
    nu = data_headers[0].Rows

**Comment by debugwangz** [comment]
The idx_proj_start is bigger than the actual biggest index
